baseURL: "https://forbiddencactus.github.io"
title: Alex Griffin
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: "I am a games programmer who specialises in computer graphics.
consequat."
    author: Alexis Griffin
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alex Griffin
          subtitle: "I'm a game developer! I specialise in real time rendering and game engine development."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Alexis Griffin
          buttons:
    socialIcons:
        - name: LinkedIn
          url: https://www.linkedin.com/in/forbiddencactus/
        - name: GitHub
          url: https://github.com/forbiddencactus
        - name: Twitter
          url: https://twitter.com/forbiddencactus
        - name: Instagram
          url: https://www.instagram.com/forbiddencacti/


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Prof. Name"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
