baseURL: "https://forbiddencactus.github.io"
title: Alex Griffin
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: "I am a Professor of Subject at the University of Place. My research covers various topics.
consequat."
    author: Alexis Griffin
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alex Griffin
          subtitle: "I'm a game developer and designer! I specialise in topics like graphics programming and rendering pipelines, general game engine development, and gameplay programming. I'm very comfortable with low level 'on the metal' programming, DOD, and efficient, manual memory management techniques that keep the cache/hardware happy, and the program running smoothly."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Alexis Griffin
          buttons:
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:pascal.michaillat@gmail.com
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Substack
          url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Prof. Name"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
